// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: vizor_demonstration.proto
#ifndef GRPC_vizor_5fdemonstration_2eproto__INCLUDED
#define GRPC_vizor_5fdemonstration_2eproto__INCLUDED

#include "vizor_demonstration.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace vizor_proto_demostration {

class HelloService final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Hello(::grpc::ClientContext* context, const ::vizor_proto_demostration::HelloRequest& request, ::vizor_proto_demostration::HelloResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vizor_proto_demostration::HelloResponse>> AsyncHello(::grpc::ClientContext* context, const ::vizor_proto_demostration::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vizor_proto_demostration::HelloResponse>>(AsyncHelloRaw(context, request, cq));
    }
    virtual ::grpc::Status ServerTime(::grpc::ClientContext* context, const ::vizor_proto_demostration::ServerTimeRequest& request, ::vizor_proto_demostration::ServerTimeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vizor_proto_demostration::ServerTimeResponse>> AsyncServerTime(::grpc::ClientContext* context, const ::vizor_proto_demostration::ServerTimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::vizor_proto_demostration::ServerTimeResponse>>(AsyncServerTimeRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vizor_proto_demostration::HelloResponse>* AsyncHelloRaw(::grpc::ClientContext* context, const ::vizor_proto_demostration::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::vizor_proto_demostration::ServerTimeResponse>* AsyncServerTimeRaw(::grpc::ClientContext* context, const ::vizor_proto_demostration::ServerTimeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Hello(::grpc::ClientContext* context, const ::vizor_proto_demostration::HelloRequest& request, ::vizor_proto_demostration::HelloResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vizor_proto_demostration::HelloResponse>> AsyncHello(::grpc::ClientContext* context, const ::vizor_proto_demostration::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vizor_proto_demostration::HelloResponse>>(AsyncHelloRaw(context, request, cq));
    }
    ::grpc::Status ServerTime(::grpc::ClientContext* context, const ::vizor_proto_demostration::ServerTimeRequest& request, ::vizor_proto_demostration::ServerTimeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vizor_proto_demostration::ServerTimeResponse>> AsyncServerTime(::grpc::ClientContext* context, const ::vizor_proto_demostration::ServerTimeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::vizor_proto_demostration::ServerTimeResponse>>(AsyncServerTimeRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::vizor_proto_demostration::HelloResponse>* AsyncHelloRaw(::grpc::ClientContext* context, const ::vizor_proto_demostration::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::vizor_proto_demostration::ServerTimeResponse>* AsyncServerTimeRaw(::grpc::ClientContext* context, const ::vizor_proto_demostration::ServerTimeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_Hello_;
    const ::grpc::RpcMethod rpcmethod_ServerTime_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Hello(::grpc::ServerContext* context, const ::vizor_proto_demostration::HelloRequest* request, ::vizor_proto_demostration::HelloResponse* response);
    virtual ::grpc::Status ServerTime(::grpc::ServerContext* context, const ::vizor_proto_demostration::ServerTimeRequest* request, ::vizor_proto_demostration::ServerTimeResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Hello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* context, const ::vizor_proto_demostration::HelloRequest* request, ::vizor_proto_demostration::HelloResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHello(::grpc::ServerContext* context, ::vizor_proto_demostration::HelloRequest* request, ::grpc::ServerAsyncResponseWriter< ::vizor_proto_demostration::HelloResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ServerTime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_ServerTime() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ServerTime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerTime(::grpc::ServerContext* context, const ::vizor_proto_demostration::ServerTimeRequest* request, ::vizor_proto_demostration::ServerTimeResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestServerTime(::grpc::ServerContext* context, ::vizor_proto_demostration::ServerTimeRequest* request, ::grpc::ServerAsyncResponseWriter< ::vizor_proto_demostration::ServerTimeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Hello<WithAsyncMethod_ServerTime<Service > > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Hello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Hello(::grpc::ServerContext* context, const ::vizor_proto_demostration::HelloRequest* request, ::vizor_proto_demostration::HelloResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ServerTime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_ServerTime() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ServerTime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ServerTime(::grpc::ServerContext* context, const ::vizor_proto_demostration::ServerTimeRequest* request, ::vizor_proto_demostration::ServerTimeResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Hello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Hello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::vizor_proto_demostration::HelloRequest, ::vizor_proto_demostration::HelloResponse>(std::bind(&WithStreamedUnaryMethod_Hello<BaseClass>::StreamedHello, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Hello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Hello(::grpc::ServerContext* context, const ::vizor_proto_demostration::HelloRequest* request, ::vizor_proto_demostration::HelloResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHello(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vizor_proto_demostration::HelloRequest,::vizor_proto_demostration::HelloResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ServerTime : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_ServerTime() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::StreamedUnaryHandler< ::vizor_proto_demostration::ServerTimeRequest, ::vizor_proto_demostration::ServerTimeResponse>(std::bind(&WithStreamedUnaryMethod_ServerTime<BaseClass>::StreamedServerTime, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ServerTime() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ServerTime(::grpc::ServerContext* context, const ::vizor_proto_demostration::ServerTimeRequest* request, ::vizor_proto_demostration::ServerTimeResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedServerTime(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::vizor_proto_demostration::ServerTimeRequest,::vizor_proto_demostration::ServerTimeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Hello<WithStreamedUnaryMethod_ServerTime<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Hello<WithStreamedUnaryMethod_ServerTime<Service > > StreamedService;
};

}  // namespace vizor_proto_demostration


#endif  // GRPC_vizor_5fdemonstration_2eproto__INCLUDED
