# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vizor_demonstration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vizor_demonstration.proto',
  package='vizor_proto_demostration',
  syntax='proto3',
  serialized_pb=_b('\n\x19vizor_demonstration.proto\x12\x18vizor_proto_demostration\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x13\n\x11ServerTimeRequest\"i\n\x12ServerTimeResponse\x12\r\n\x05hours\x18\x02 \x01(\r\x12\x0f\n\x07minutes\x18\x03 \x01(\r\x12\x0f\n\x07seconds\x18\x04 \x01(\r\x12\x10\n\x08timezone\x18\x05 \x01(\t\x12\x10\n\x08location\x18\x06 \x01(\t2\xd5\x01\n\x0cHelloService\x12Z\n\x05Hello\x12&.vizor_proto_demostration.HelloRequest\x1a\'.vizor_proto_demostration.HelloResponse\"\x00\x12i\n\nServerTime\x12+.vizor_proto_demostration.ServerTimeRequest\x1a,.vizor_proto_demostration.ServerTimeResponse\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='vizor_proto_demostration.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='vizor_proto_demostration.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=83,
)


_HELLORESPONSE = _descriptor.Descriptor(
  name='HelloResponse',
  full_name='vizor_proto_demostration.HelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='vizor_proto_demostration.HelloResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=117,
)


_SERVERTIMEREQUEST = _descriptor.Descriptor(
  name='ServerTimeRequest',
  full_name='vizor_proto_demostration.ServerTimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=138,
)


_SERVERTIMERESPONSE = _descriptor.Descriptor(
  name='ServerTimeResponse',
  full_name='vizor_proto_demostration.ServerTimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hours', full_name='vizor_proto_demostration.ServerTimeResponse.hours', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minutes', full_name='vizor_proto_demostration.ServerTimeResponse.minutes', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seconds', full_name='vizor_proto_demostration.ServerTimeResponse.seconds', index=2,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timezone', full_name='vizor_proto_demostration.ServerTimeResponse.timezone', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='location', full_name='vizor_proto_demostration.ServerTimeResponse.location', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=245,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloResponse'] = _HELLORESPONSE
DESCRIPTOR.message_types_by_name['ServerTimeRequest'] = _SERVERTIMEREQUEST
DESCRIPTOR.message_types_by_name['ServerTimeResponse'] = _SERVERTIMERESPONSE

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'vizor_demonstration_pb2'
  # @@protoc_insertion_point(class_scope:vizor_proto_demostration.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloResponse = _reflection.GeneratedProtocolMessageType('HelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _HELLORESPONSE,
  __module__ = 'vizor_demonstration_pb2'
  # @@protoc_insertion_point(class_scope:vizor_proto_demostration.HelloResponse)
  ))
_sym_db.RegisterMessage(HelloResponse)

ServerTimeRequest = _reflection.GeneratedProtocolMessageType('ServerTimeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SERVERTIMEREQUEST,
  __module__ = 'vizor_demonstration_pb2'
  # @@protoc_insertion_point(class_scope:vizor_proto_demostration.ServerTimeRequest)
  ))
_sym_db.RegisterMessage(ServerTimeRequest)

ServerTimeResponse = _reflection.GeneratedProtocolMessageType('ServerTimeResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVERTIMERESPONSE,
  __module__ = 'vizor_demonstration_pb2'
  # @@protoc_insertion_point(class_scope:vizor_proto_demostration.ServerTimeResponse)
  ))
_sym_db.RegisterMessage(ServerTimeResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class HelloServiceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Hello = channel.unary_unary(
          '/vizor_proto_demostration.HelloService/Hello',
          request_serializer=HelloRequest.SerializeToString,
          response_deserializer=HelloResponse.FromString,
          )
      self.ServerTime = channel.unary_unary(
          '/vizor_proto_demostration.HelloService/ServerTime',
          request_serializer=ServerTimeRequest.SerializeToString,
          response_deserializer=ServerTimeResponse.FromString,
          )


  class HelloServiceServicer(object):

    def Hello(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ServerTime(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_HelloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Hello': grpc.unary_unary_rpc_method_handler(
            servicer.Hello,
            request_deserializer=HelloRequest.FromString,
            response_serializer=HelloResponse.SerializeToString,
        ),
        'ServerTime': grpc.unary_unary_rpc_method_handler(
            servicer.ServerTime,
            request_deserializer=ServerTimeRequest.FromString,
            response_serializer=ServerTimeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'vizor_proto_demostration.HelloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaHelloServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Hello(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ServerTime(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaHelloServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Hello(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Hello.future = None
    def ServerTime(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    ServerTime.future = None


  def beta_create_HelloService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('vizor_proto_demostration.HelloService', 'Hello'): HelloRequest.FromString,
      ('vizor_proto_demostration.HelloService', 'ServerTime'): ServerTimeRequest.FromString,
    }
    response_serializers = {
      ('vizor_proto_demostration.HelloService', 'Hello'): HelloResponse.SerializeToString,
      ('vizor_proto_demostration.HelloService', 'ServerTime'): ServerTimeResponse.SerializeToString,
    }
    method_implementations = {
      ('vizor_proto_demostration.HelloService', 'Hello'): face_utilities.unary_unary_inline(servicer.Hello),
      ('vizor_proto_demostration.HelloService', 'ServerTime'): face_utilities.unary_unary_inline(servicer.ServerTime),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_HelloService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('vizor_proto_demostration.HelloService', 'Hello'): HelloRequest.SerializeToString,
      ('vizor_proto_demostration.HelloService', 'ServerTime'): ServerTimeRequest.SerializeToString,
    }
    response_deserializers = {
      ('vizor_proto_demostration.HelloService', 'Hello'): HelloResponse.FromString,
      ('vizor_proto_demostration.HelloService', 'ServerTime'): ServerTimeResponse.FromString,
    }
    cardinalities = {
      'Hello': cardinality.Cardinality.UNARY_UNARY,
      'ServerTime': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'vizor_proto_demostration.HelloService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
