# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import vizor_demonstration_pb2 as vizor__demonstration__pb2


class HelloServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Hello = channel.unary_unary(
        '/vizor_proto_demostration.HelloService/Hello',
        request_serializer=vizor__demonstration__pb2.HelloRequest.SerializeToString,
        response_deserializer=vizor__demonstration__pb2.HelloResponse.FromString,
        )
    self.ServerTime = channel.unary_unary(
        '/vizor_proto_demostration.HelloService/ServerTime',
        request_serializer=vizor__demonstration__pb2.ServerTimeRequest.SerializeToString,
        response_deserializer=vizor__demonstration__pb2.ServerTimeResponse.FromString,
        )


class HelloServiceServicer(object):

  def Hello(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ServerTime(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Hello': grpc.unary_unary_rpc_method_handler(
          servicer.Hello,
          request_deserializer=vizor__demonstration__pb2.HelloRequest.FromString,
          response_serializer=vizor__demonstration__pb2.HelloResponse.SerializeToString,
      ),
      'ServerTime': grpc.unary_unary_rpc_method_handler(
          servicer.ServerTime,
          request_deserializer=vizor__demonstration__pb2.ServerTimeRequest.FromString,
          response_serializer=vizor__demonstration__pb2.ServerTimeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'vizor_proto_demostration.HelloService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
